name: Update Test cases

on:
  workflow_dispatch:
  schedule:
    # Run weekly, on Monday morning at 05:00 UTC.
    # Problems are reported to the latest editor of the script,
    # currently https://github.com/Jym77
    - cron: '0 5 * * 1'

jobs:
  update-act:
    name: Update ACT rules test cases
    runs-on: ubuntu-latest
    steps:
      # Set up repository and code
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.A11Y_PUBLIC_GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: yarn-${{ hashFiles('yarn.lock') }}
      - run: >
          yarn config set
          npmScopes.siteimprove.npmAuthToken
          ${{ secrets.GITHUB_TOKEN }}
      - run: yarn install --immutable
      - run: yarn dedupe
      - run: yarn build
      # Update test cases, run tests
      - run: yarn fixtures
      - run: yarn test

      # If we made it thus far, commit changes to the repository
      - run: |
          git config --local core.filemode false
          # See https://api.github.com/users/siteimprove-builduser
          git config --local user.name "siteimprove-builduser"
          git config --local user.email "8577410+siteimprove-builduser@users.noreply.github.com"
      # .yarnrc.yml got the AuthToken added, which we need to totally ignore
      - run: git checkout -- .yarnrc.yml
      - run: git add test/fixtures reports
      # Check if changes have been made, commit and push
      - run: git diff-index --quiet HEAD || git commit -m "Update ACT test cases" --no-verify
      - run: git push

      # If we made it thus far, run tests in strict mode to trigger an error and call for
      # action on updating the exceptions
      - run: yarn strict

